/*
** Generated by Sun ONE Studio X-Designer
*/
#ifndef _createmovie_h
#define _createmovie_h

#define XD_MOTIF




extern Widget shell2;
extern Widget OpenDialog;

extern Widget S_CreateMovie;
extern Widget createMovieDT;
extern Widget Start;
extern Widget Cancel;
extern Widget Help;
extern Widget rowcolCreateMovie;
extern Widget frameImages;
extern Widget rowcolImages;
extern Widget TB_ImageFile;
extern Widget optImageFormat;
extern Widget TIFF;
extern Widget JPG;
extern Widget RGB;
extern Widget GIF;
extern Widget OutputLabelImage;
extern Widget OutputFilename;
extern Widget SaveAsImages;
extern Widget frameMovie;
extern Widget SaveAsMovie;
extern Widget rowcolMovie;
extern Widget TB_MovieFile;
extern Widget MovieFormat;
extern Widget FileFormat;
extern Widget AviMovie;
extern Widget Quicktime;
extern Widget SGIMovie;
extern Widget OutputLabel;
extern Widget OutputMovie;

extern void create_shell2 (Display *, char *, int, char **);


extern void create_S_CreateMovie (Widget);
void CreateMovieCallback(Widget, XtPointer, XtPointer);

/* Global Variables Generated into Main Module */

extern XtAppContext app_context ;
extern Display     *display ;


#endif
