/*
** Generated by Sun ONE Studio X-Designer
*/
/*
**LIBS: -lXm -lXt -lX11
*/

#include <stdlib.h>
#include <X11/Xatom.h>
#include <X11/Intrinsic.h>
#include <X11/Shell.h>

#include <Xm/Xm.h>
#include <Xm/DialogS.h>
#include <Xm/Frame.h>
#include <Xm/Label.h>
#include <Xm/MessageB.h>
#include <Xm/PushB.h>
#include <Xm/RowColumn.h>
#include <Xm/TextF.h>
#include <Xm/ToggleB.h>
#include <Xm/CascadeBG.h>
#include <Xm/LabelG.h>
#include <Xm/SeparatoG.h>


#include "createmovie.h"
#include "color3d.h"

extern void popupCallback(Widget, XtPointer, XtPointer) ;
extern void openDialogCallback(Widget, XtPointer, XtPointer) ;
extern void startCallback(Widget, XtPointer, XtPointer) ;
extern void cancelCallback(Widget, XtPointer, XtPointer) ;
extern void helpCallback(Widget, XtPointer, XtPointer) ;
extern void selectImageCallback(Widget, XtPointer, XtPointer) ;
extern void tiffCallback(Widget, XtPointer, XtPointer) ;
extern void jpgCallback(Widget, XtPointer, XtPointer) ;
extern void rgbCallback(Widget, XtPointer, XtPointer) ;
extern void gifCallback(Widget, XtPointer, XtPointer) ;
extern void outputImageCallback(Widget, XtPointer, XtPointer) ;
extern void focusImageCallback(Widget, XtPointer, XtPointer) ;
extern void selectMovieCallback(Widget, XtPointer, XtPointer) ;
extern void avimovieCallback(Widget, XtPointer, XtPointer) ;
extern void quicktimeCallback(Widget, XtPointer, XtPointer) ;
extern void sgimovieCallback(Widget, XtPointer, XtPointer) ;
extern void outputMovieCallback(Widget, XtPointer, XtPointer) ;
extern void focusMovieCallback(Widget, XtPointer, XtPointer) ;

static Widget xd_links [ 1 ];

void XDmanage_link( Widget w, XtPointer client_data, XtPointer call_data)
{
	if (client_data && *(Widget *) client_data)
		XtManageChild(*(Widget *) client_data);
}

void XDunmanage_link( Widget w, XtPointer client_data, XtPointer call_data)
{
	if (client_data && *(Widget *) client_data)
		XtUnmanageChild(*(Widget *) client_data);
}

void XDpopup_link( Widget w, XtPointer client_data, XtPointer call_data)
{
	if (client_data && *(Widget *) client_data)
		XtPopup(*(Widget *) client_data, XtGrabNone);
}

void XDpopdown_link( Widget w, XtPointer client_data, XtPointer call_data)
{
	if (client_data && *(Widget *) client_data)
		XtPopdown(*(Widget *) client_data);
}

void XDmap_link( Widget w, XtPointer client_data, XtPointer call_data)
{
	if (client_data && *(Widget *) client_data)
		XtMapWidget(*(Widget *) client_data);
}

void XDunmap_link( Widget w, XtPointer client_data, XtPointer call_data)
{
	if (client_data && *(Widget *) client_data)
		XtUnmapWidget(*(Widget *) client_data);
}

void XDenable_link( Widget w, XtPointer client_data, XtPointer call_data)
{
	if (client_data && *(Widget *) client_data)
		XtSetSensitive(*(Widget *) client_data, TRUE);
}

void XDdisable_link( Widget w, XtPointer client_data, XtPointer call_data)
{
	if (client_data && *(Widget *) client_data)
		XtSetSensitive(*(Widget *) client_data, FALSE);
}

Widget shell2 = (Widget) NULL;
Widget OpenDialog = (Widget) NULL;
Widget S_CreateMovie = (Widget) NULL;
Widget createMovieDT = (Widget) NULL;
Widget Start = (Widget) NULL;
Widget Cancel = (Widget) NULL;
static Widget Help = (Widget) NULL;
Widget rowcolCreateMovie = (Widget) NULL;
Widget frameImages = (Widget) NULL;
Widget rowcolImages = (Widget) NULL;
Widget TB_ImageFile = (Widget) NULL;
Widget optImageFormat = (Widget) NULL;
Widget TIFF = (Widget) NULL;
Widget JPG = (Widget) NULL;
Widget RGB = (Widget) NULL;
Widget GIF = (Widget) NULL;
Widget OutputLabelImage = (Widget) NULL;
Widget OutputFilename = (Widget) NULL;
Widget SaveAsImages = (Widget) NULL;
Widget frameMovie = (Widget) NULL;
Widget SaveAsMovie = (Widget) NULL;
Widget rowcolMovie = (Widget) NULL;
Widget TB_MovieFile = (Widget) NULL;
Widget MovieFormat = (Widget) NULL;
Widget FileFormat = (Widget) NULL;
Widget AviMovie = (Widget) NULL;
Widget Quicktime = (Widget) NULL;
Widget SGIMovie = (Widget) NULL;
Widget OutputLabel = (Widget) NULL;
Widget OutputMovie = (Widget) NULL;



void create_shell2 (Display *display, char *app_name, int app_argc, char **app_argv)
{
	Widget children[1];      /* Children to manage */
	Arg al[64];                    /* Arg List */
	register int ac = 0;           /* Arg Count */
	XtPointer tmp_value;             /* ditto */

	XtSetArg(al[ac], XmNallowShellResize, TRUE); ac++;
	XtSetArg(al[ac], XmNargc, app_argc); ac++;
	XtSetArg(al[ac], XmNargv, app_argv); ac++;
	shell2 = XtAppCreateShell(app_name, (char *) "XApplication", applicationShellWidgetClass, display, al, ac);

	ac = 0;
	if (shell2)
		XtAddCallback( shell2, XmNpopupCallback, popupCallback, (XtPointer) 0 );
	OpenDialog = XmCreatePushButton ( shell2, (char *) "Open Dialog", al, ac );

	XtAddCallback (OpenDialog, XmNactivateCallback, XDmanage_link, (XtPointer) &xd_links[0] );
	if (OpenDialog)
		XtAddCallback( OpenDialog, XmNactivateCallback, openDialogCallback, (XtPointer) 0 );
	if (OpenDialog != (Widget) 0) { XtManageChild ( OpenDialog); }
}

void 
CreateMovieCallback( Widget w, XtPointer clientData, XtPointer callData )
{
  char *temp;
  char *filename;
  XDmanage_link(w, (XtPointer) xd_links[0], callData);
 
  /* set resources */
  temp = strdup(g_loesung.dateiname);
  filename = strtok(temp, ".");
  XtVaSetValues(OutputFilename, XmNvalue, filename, NULL);
  XtVaSetValues(OutputMovie, XmNvalue, filename, NULL);
  free(temp);
}

void create_S_CreateMovie (Widget parent)
{
	Widget children[5];      /* Children to manage */
	Arg al[64];                    /* Arg List */
	register int ac = 0;           /* Arg Count */
	XtPointer tmp_value;             /* ditto */
	XmString xmstrings[16];    /* temporary storage for XmStrings */
	Widget label1 = (Widget)NULL;
	Widget cascade1 = (Widget)NULL;
	Widget menu2 = (Widget)NULL;
	Widget cascade2 = (Widget)NULL;
	Widget menu1 = (Widget)NULL;

	XtSetArg(al[ac], XmNallowShellResize, TRUE); ac++;
	S_CreateMovie = XmCreateDialogShell ( parent, (char *) "S_CreateMovie", al, ac );
	ac = 0;
	XtSetArg(al[ac], XmNautoUnmanage, FALSE); ac++;
	XtSetArg(al[ac], XmNdialogType, XmDIALOG_TEMPLATE); ac++;
	createMovieDT = XmCreateMessageBox ( S_CreateMovie, (char *) "createMovieDT", al, ac );
	ac = 0;
	Start = XmCreatePushButton ( createMovieDT, (char *) "Start", al, ac );
	Cancel = XmCreatePushButton ( createMovieDT, (char *) "Cancel", al, ac );
	Help = XmCreatePushButton ( createMovieDT, (char *) "Help", al, ac );
	rowcolCreateMovie = XmCreateRowColumn ( createMovieDT, (char *) "rowcolCreateMovie", al, ac );
	frameImages = XmCreateFrame ( rowcolCreateMovie, (char *) "frameImages", al, ac );
	rowcolImages = XmCreateRowColumn ( frameImages, (char *) "rowcolImages", al, ac );
	xmstrings[0] = XmStringCreateLtoR ( "Image File", XmFONTLIST_DEFAULT_TAG );
	XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
	TB_ImageFile = XmCreateToggleButton ( rowcolImages, (char *) "TB_ImageFile", al, ac );
	ac = 0;
	XmStringFree ( xmstrings [ 0 ] );
	optImageFormat = XmCreateOptionMenu ( rowcolImages, (char *) "optImageFormat", al, ac );
	label1 = XmOptionLabelGadget ( optImageFormat );
	cascade1 = XmOptionButtonGadget ( optImageFormat );
	menu2 = XmCreatePulldownMenu ( optImageFormat, (char *) "menu2", al, ac );
	TIFF = XmCreatePushButton ( menu2, (char *) "TIFF", al, ac );
	JPG = XmCreatePushButton ( menu2, (char *) "JPG", al, ac );
	RGB = XmCreatePushButton ( menu2, (char *) "RGB", al, ac );
	GIF = XmCreatePushButton ( menu2, (char *) "GIF", al, ac );
	xmstrings[0] = XmStringCreateLtoR ( "Output File Name", XmFONTLIST_DEFAULT_TAG  );
	XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
	XtSetArg(al[ac], XmNalignment, XmALIGNMENT_CENTER); ac++;
	OutputLabelImage = XmCreateLabel ( rowcolImages, (char *) "OutputLabelImage", al, ac );
	ac = 0;
	XmStringFree ( xmstrings [ 0 ] );
	OutputFilename = XmCreateTextField ( rowcolImages, (char *) "OutputFilename", al, ac );
	XtSetArg(al[ac], XmNchildType, XmFRAME_TITLE_CHILD); ac++;
	xmstrings[0] = XmStringCreateLtoR ( "Save As Images", XmFONTLIST_DEFAULT_TAG  );
	XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
	SaveAsImages = XmCreateLabel ( frameImages, (char *) "SaveAsImages", al, ac );
	ac = 0;
	XmStringFree ( xmstrings [ 0 ] );
	frameMovie = XmCreateFrame ( rowcolCreateMovie, (char *) "frameMovie", al, ac );
	XtSetArg(al[ac], XmNchildType, XmFRAME_TITLE_CHILD); ac++;
	xmstrings[0] = XmStringCreateLtoR ( "Save As Movie", XmFONTLIST_DEFAULT_TAG  );
	XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
	SaveAsMovie = XmCreateLabel ( frameMovie, (char *) "SaveAsMovie", al, ac );
	ac = 0;
	XmStringFree ( xmstrings [ 0 ] );
	rowcolMovie = XmCreateRowColumn ( frameMovie, (char *) "rowcolMovie", al, ac );
	xmstrings[0] = XmStringCreateLtoR ( "Movie File", XmFONTLIST_DEFAULT_TAG  );
	XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
	TB_MovieFile = XmCreateToggleButton ( rowcolMovie, (char *) "TB_MovieFile", al, ac );
	ac = 0;
	XmStringFree ( xmstrings [ 0 ] );
	MovieFormat = XmCreateOptionMenu ( rowcolMovie, (char *) "MovieFormat", al, ac );
	FileFormat = XmOptionLabelGadget ( MovieFormat );
	cascade2 = XmOptionButtonGadget ( MovieFormat );
	menu1 = XmCreatePulldownMenu ( MovieFormat, (char *) "menu1", al, ac );
	AviMovie = XmCreatePushButton ( menu1, (char *) "AviMovie", al, ac );
	Quicktime = XmCreatePushButton ( menu1, (char *) "Quicktime", al, ac );
	SGIMovie = XmCreatePushButton ( menu1, (char *) "SGIMovie", al, ac );
	XtSetArg(al[ac], XmNalignment, XmALIGNMENT_CENTER); ac++;
	OutputLabel = XmCreateLabel ( rowcolMovie, (char *) "Output File Name", al, ac );
	ac = 0;
	OutputMovie = XmCreateTextField ( rowcolMovie, (char *) "OutputMovie", al, ac );
	xd_links [0] = createMovieDT;

	if (Start)
		XtAddCallback( Start, XmNactivateCallback, startCallback, (XtPointer) 0 );
	if (Cancel)
		XtAddCallback( Cancel, XmNactivateCallback, cancelCallback, (XtPointer) &createMovieDT );
	if (Help)
		XtAddCallback( Help, XmNhelpCallback, helpCallback, (XtPointer) 0 );
	if (Help)
		XtAddCallback( Help, XmNactivateCallback, helpCallback, (XtPointer) 0 );
	if (TB_ImageFile)
		XtAddCallback( TB_ImageFile, XmNvalueChangedCallback, selectImageCallback, (XtPointer) &rowcolImages );
	if (TIFF)
		XtAddCallback( TIFF, XmNactivateCallback, tiffCallback, (XtPointer) 0 );
	if (JPG)
		XtAddCallback( JPG, XmNactivateCallback, jpgCallback, (XtPointer) 0 );
	if (RGB)
		XtAddCallback( RGB, XmNactivateCallback, rgbCallback, (XtPointer) 0 );
	if (GIF)
		XtAddCallback( GIF, XmNactivateCallback, gifCallback, (XtPointer) 0 );
	if ((children[ac] = TIFF) != (Widget) 0) { ac++; }
	if ((children[ac] = JPG) != (Widget) 0) { ac++; }
	if ((children[ac] = RGB) != (Widget) 0) { ac++; }
	if ((children[ac] = GIF) != (Widget) 0) { ac++; }
	if (ac > 0) { XtManageChildren(children, ac); }
	ac = 0;
	XtSetArg(al[ac], XmNsubMenuId, menu2); ac++;
	XtSetValues(cascade1, al, ac );
	ac = 0;
	if (OutputFilename)
		XtAddCallback( OutputFilename, XmNvalueChangedCallback, outputImageCallback, (XtPointer) 0 );
	if (OutputFilename) 
	  XtVaSetValues( OutputFilename, XmNvalue, g_loesung.dateiname, NULL );
	if ((children[ac] = TB_ImageFile) != (Widget) 0) { ac++; }
	if ((children[ac] = optImageFormat) != (Widget) 0) { ac++; }
	if ((children[ac] = OutputLabelImage) != (Widget) 0) { ac++; }
	if ((children[ac] = OutputFilename) != (Widget) 0) { ac++; }
	if (ac > 0) { XtManageChildren(children, ac); }
	ac = 0;
	if ((children[ac] = rowcolImages) != (Widget) 0) { ac++; }
	if ((children[ac] = SaveAsImages) != (Widget) 0) { ac++; }
	if (ac > 0) { XtManageChildren(children, ac); }
	ac = 0;
	if (TB_MovieFile)
		XtAddCallback( TB_MovieFile, XmNvalueChangedCallback, selectMovieCallback, (XtPointer) &rowcolMovie );
	if (AviMovie)
		XtAddCallback( AviMovie, XmNactivateCallback, avimovieCallback, (XtPointer) 0 );
	if (Quicktime)
		XtAddCallback( Quicktime, XmNactivateCallback, quicktimeCallback, (XtPointer) 0 );
	if (SGIMovie)
		XtAddCallback( SGIMovie, XmNactivateCallback, sgimovieCallback, (XtPointer) 0 );
	if ((children[ac] = AviMovie) != (Widget) 0) { ac++; }
	if ((children[ac] = Quicktime) != (Widget) 0) { ac++; }
	if ((children[ac] = SGIMovie) != (Widget) 0) { ac++; }
	if (ac > 0) { XtManageChildren(children, ac); }
	ac = 0;
	XtSetArg(al[ac], XmNsubMenuId, menu1); ac++;
	XtSetValues(cascade2, al, ac );
	ac = 0;
	if (OutputMovie)
		XtAddCallback( OutputMovie, XmNvalueChangedCallback, outputMovieCallback, (XtPointer) 0 );
	if (OutputMovie) 
	  XtVaSetValues( OutputMovie, XmNvalue, g_loesung.dateiname, NULL );
	if ((children[ac] = TB_MovieFile) != (Widget) 0) { ac++; }
	if ((children[ac] = MovieFormat) != (Widget) 0) { ac++; }
	if ((children[ac] = OutputLabel) != (Widget) 0) { ac++; }
	if ((children[ac] = OutputMovie) != (Widget) 0) { ac++; }
	if (ac > 0) { XtManageChildren(children, ac); }
	ac = 0;
	if ((children[ac] = SaveAsMovie) != (Widget) 0) { ac++; }
	if ((children[ac] = rowcolMovie) != (Widget) 0) { ac++; }
	if (ac > 0) { XtManageChildren(children, ac); }
	ac = 0;
	if ((children[ac] = frameImages) != (Widget) 0) { ac++; }
	if ((children[ac] = frameMovie) != (Widget) 0) { ac++; }
	if (ac > 0) { XtManageChildren(children, ac); }
	ac = 0;
	if ((children[ac] = Start) != (Widget) 0) { ac++; }
	if ((children[ac] = Cancel) != (Widget) 0) { ac++; }
	if ((children[ac] = Help) != (Widget) 0) { ac++; }
	if ((children[ac] = rowcolCreateMovie) != (Widget) 0) { ac++; }
	if (ac > 0) { XtManageChildren(children, ac); }
	ac = 0;

}

