/*
** Generated by Sun ONE Studio X-Designer
*/

/*
** Sun ONE Studio X-Designer-generated prelude.
** Do not edit lines before "End of Sun ONE Studio X-Designer generated prelude"
** Lines beginning ** Sun ONE Studio X-Designer Stub indicate a stub
** which will not be output on re-generation
*/

/*
**LIBS: -lXm -lXt -lX11
*/

#include <stdlib.h>
#include <X11/Xatom.h>
#include <X11/Intrinsic.h>
#include <X11/Shell.h>

#include <Xm/Xm.h>
#include <Xm/DialogS.h>
#include <Xm/PushB.h>
#include <Xm/TextF.h>
#include <Xm/ToggleB.h>

#include "color3d.h"
#include "grafik.h"
#include "createmovie.h"
#include "strukturen.h"
#include "image.h"

extern void XDmanage_link( Widget w, XtPointer client_data, XtPointer call_data);
extern void XDunmanage_link( Widget w, XtPointer client_data, XtPointer call_data);
extern void XDpopup_link( Widget w, XtPointer client_data, XtPointer call_data);
extern void XDpopdown_link( Widget w, XtPointer client_data, XtPointer call_data);
extern void XDmap_link( Widget w, XtPointer client_data, XtPointer call_data);
extern void XDunmap_link( Widget w, XtPointer client_data, XtPointer call_data);
extern void XDenable_link( Widget w, XtPointer client_data, XtPointer call_data);
extern void XDdisable_link( Widget w, XtPointer client_data, XtPointer call_data);
static void savepicture(char *name, int width, int height, int format); 
static t_bool image;
static t_bool movie;
static char imagename[256];
static char moviename[256];

static enum imageformat{
  IMGRGB = -3,
  IMGTIF = -5,
  IMGEPS = -6,
  IMGBMP = -9,
  IMGGIF = -10,
  IMGJPG = -11
};
enum imageformat imgformat = IMGTIF;

static enum {
  SGI = 1,
  MOV,
  AVI
} movformat;

/* End of Sun ONE Studio X-Designer generated prelude */
/*
** Sun ONE Studio X-Designer Stub cancelCallback
*/

void cancelCallback(Widget w, XtPointer client_data, XtPointer xt_call_data)
{
  XmPushButtonCallbackStruct *call_data = (XmPushButtonCallbackStruct *) xt_call_data ;
  animation_stop();
  XDunmanage_link( w, client_data, xt_call_data);
}

/*
** Sun ONE Studio X-Designer Stub helpCallback
*/

void helpCallback(Widget w, XtPointer client_data, XtPointer xt_call_data)
{
  XmAnyCallbackStruct *call_data = (XmAnyCallbackStruct *) xt_call_data ;
}

/*
** Sun ONE Studio X-Designer Stub startCallback
*/

void startCallback(Widget w, XtPointer client_data, XtPointer xt_call_data)
{
	XmPushButtonCallbackStruct *call_data = (XmPushButtonCallbackStruct *) xt_call_data ;

	/* we save movie or image */
	if ( image )
	{
		int i;

		for (i = 0; i < g_animation.anim_ende; i++)
		{
			if (next_zeit_cb())
				savepicture(imagename, C3D_win.gl_width, C3D_win.gl_height, imgformat);
		}
	}
	else if ( movie )
	{

	}

}

static void
savepicture(char *name, int width, int height, int format)
{
	char *temp;
	char *file_name;
	char *buf;

	if (name == NULL)
	{
		temp = strdup(g_loesung.dateiname);
		file_name = strtok(temp, ".");
	}
	else
	{
		temp = strdup(name);
		file_name = strtok(temp, "#");
	}
	ClearBuffers(2);
	c3d(width, height);
	glFinish();
	glXWaitX();

	/* dump picture in the file */
	if (!WindowDump(width, height, 0, format, file_name))
	{
		warning("This directory already contains file(s) saved under this name(s).\n To save new file(s), first delete existing one(s).");
	}

	glDrawBuffer(GL_BACK);
	free(temp);
}

/*
** Sun ONE Studio X-Designer Stub selectImageCallback
*/

void selectImageCallback(Widget w, XtPointer client_data, XtPointer xt_call_data)
{
	Widget optImage, outputFile;
	XmToggleButtonCallbackStruct *call_data = (XmToggleButtonCallbackStruct *) xt_call_data ;
	optImage   = XtNameToWidget( *(Widget *)client_data, "optImageFormat" );
	outputFile = XtNameToWidget( *(Widget *)client_data, "OutputFilename" );

	if (call_data->set == TRUE )
	{
		image = TRUE;
		/* set sensitive image options */
		XDenable_link( w, optImage, xt_call_data );
		XDenable_link( w, outputFile, xt_call_data );

	}
	else
	{
		image = FALSE;
		XDdisable_link( w, optImage, xt_call_data );
		XDdisable_link( w, outputFile, xt_call_data );
	}
}

/*
** Sun ONE Studio X-Designer Stub tiffCallback
*/

void tiffCallback(Widget w, XtPointer client_data, XtPointer xt_call_data)
{
	XmPushButtonCallbackStruct *call_data = (XmPushButtonCallbackStruct *) xt_call_data ;
	if ( image )
		imgformat = IMGTIF;
}

/*
** Sun ONE Studio X-Designer Stub jpgCallback
*/

void jpgCallback(Widget w, XtPointer client_data, XtPointer xt_call_data)
{
	XmPushButtonCallbackStruct *call_data = (XmPushButtonCallbackStruct *) xt_call_data ;
	if ( image )
		imgformat = IMGJPG;
}

/*
** Sun ONE Studio X-Designer Stub rgbCallback
*/

void rgbCallback(Widget w, XtPointer client_data, XtPointer xt_call_data)
{
	XmPushButtonCallbackStruct *call_data = (XmPushButtonCallbackStruct *) xt_call_data ;
	if ( image )
		imgformat = IMGRGB;
}

/*
** Sun ONE Studio X-Designer Stub gifCallback
*/

void gifCallback(Widget w, XtPointer client_data, XtPointer xt_call_data)
{
	XmPushButtonCallbackStruct *call_data = (XmPushButtonCallbackStruct *) xt_call_data ;
	if ( image )
		imgformat = IMGGIF;
}

/*
** Sun ONE Studio X-Designer Stub outputImageCallback
*/

void outputImageCallback(Widget w, XtPointer client_data, XtPointer xt_call_data)
{
	char *name;

	XmAnyCallbackStruct *call_data = (XmAnyCallbackStruct *) xt_call_data ;
	name = (char *) client_data;
	if (name == NULL)
	{
		/* get filename from text field */
		strcpy(imagename, XmTextFieldGetString(w));
	}

}

void focusImageCallback(Widget w, XtPointer client_data, XtPointer xt_call_data)
{
	char *name;
	char *name_ext;
	char *imgname;
	char ext[5];
	name_ext = strdup(g_loesung.dateiname);
	imgname  = strtok(name_ext, ".");
	strcat(imgname, "####");

	switch(imgformat)
	{
		case IMGRGB: strcat(imgname, ".rgb"); break;
		case IMGTIF: strcat(imgname, ".tif"); break;
		case IMGEPS: strcat(imgname, ".eps"); break;
		case IMGBMP: strcat(imgname, ".bmp"); break;
		case IMGGIF: strcat(imgname, ".gif"); break;
		case IMGJPG: strcat(imgname, ".jpg"); break;
		default: strcat(imgname,".tif");      break;
	}

	if (!strcmp(XmTextFieldGetString(w),""))
	{
		XtVaSetValues (w, XmNvalue, imgname, NULL);
		sprintf(imagename, "%s", imgname);
	}
	free(name_ext);
}
/*
** Sun ONE Studio X-Designer Stub selectMovieCallback
*/

void selectMovieCallback(Widget w, XtPointer client_data, XtPointer xt_call_data)
{
	Widget optMovie, outputmovie;

	XmToggleButtonCallbackStruct *call_data = (XmToggleButtonCallbackStruct *) xt_call_data ;

	optMovie    = XtNameToWidget( *(Widget *)client_data, "MovieFormat" );
	outputmovie = XtNameToWidget( *(Widget *)client_data, "OutputMovie" );

	if (call_data->set == TRUE )
	{
		movie = TRUE;
		/* set sensitive movie options */
		XDenable_link( w, optMovie, xt_call_data );
		XDenable_link( w, outputmovie, xt_call_data );

	}
	else
	{
		movie = FALSE;
		XDdisable_link( w, optMovie, xt_call_data );
		XDdisable_link( w, outputmovie, xt_call_data );
	}
}

/*
** Sun ONE Studio X-Designer Stub avimovieCallback
*/

void avimovieCallback(Widget w, XtPointer client_data, XtPointer xt_call_data)
{
	XmPushButtonCallbackStruct *call_data = (XmPushButtonCallbackStruct *) xt_call_data ;
}

/*
** Sun ONE Studio X-Designer Stub quicktimeCallback
*/

void quicktimeCallback(Widget w, XtPointer client_data, XtPointer xt_call_data)
{
  XmPushButtonCallbackStruct *call_data = (XmPushButtonCallbackStruct *) xt_call_data ;
}

/*
** Sun ONE Studio X-Designer Stub sgimovieCallback
*/

void sgimovieCallback(Widget w, XtPointer client_data, XtPointer xt_call_data)
{
  XmPushButtonCallbackStruct *call_data = (XmPushButtonCallbackStruct *) xt_call_data ;
}

/*
** Sun ONE Studio X-Designer Stub outputMovieCallback
*/

void outputMovieCallback(Widget w, XtPointer client_data, XtPointer xt_call_data)
{
	char *name;

	XmAnyCallbackStruct *call_data = (XmAnyCallbackStruct *) xt_call_data ;
	name = (char*)client_data;
	if ( name == NULL )
	{
		/* get output movie name */
		strcpy(moviename, XmTextFieldGetString(w));
	}
}

void focusMovieCallback(Widget w, XtPointer client_data, XtPointer xt_call_data)
{
	char *name;
	char *movname;
	char *name_ext;
	char ext[5];
	name = (char*) client_data;
	name_ext = strdup(g_loesung.dateiname);
	movname  = strtok(name_ext, ".");

	switch(movformat)
	{
		case SGI: strcpy(ext, ".sgi"); break;
		case MOV: strcpy(ext, ".mov"); break;
		case AVI: strcpy(ext, ".avi"); break;
	}
	strcat(movname, ext);

	if (!strcmp(XmTextFieldGetString(w),""))
	{
		XtVaSetValues(w, XmNvalue, movname, NULL);
		sprintf(moviename, "%s", movname);
	}
}

/*
** Sun ONE Studio X-Designer Stub popupCallback
*/

void popupCallback(Widget w, XtPointer client_data, XtPointer call_data)
{
}

/*
** Sun ONE Studio X-Designer Stub openDialogCallback
*/

void openDialogCallback(Widget w, XtPointer client_data, XtPointer xt_call_data)
{
  XmPushButtonCallbackStruct *call_data = (XmPushButtonCallbackStruct *) xt_call_data ;
  if (S_CreateMovie) {
    XtManageChild(S_CreateMovie);
    XtPopup(S_CreateMovie, XtGrabNone);
  }
}

