/* ============================================================= */
/* COLOR3D - OpenGl-Version 0.1                                  */
/* ============================================================= */
/*                                                               */
/* Verfasser:   Helmut Vor & Toni Ivas                           */
/* Datum    :   10.10.03                                         */
/* Dateiname:                                                    */
/*                                                               */
/* Routinenname                         | Funktion               */
/* ------------------------------------------------------------- */
/*                                      |                        */
/*                                      |                        */
/*                                      |                        */
/*                                      |                        */
/*                                                               */
/* Includes :                                                    */
/* ==========                                                    */ 
#include <stdio.h>
#include <stdlib.h>
#include "memory.h"

//#include<Xm/Xm.h>
//#include<Mrm/MrmPublic.h>

/* Header data for different widget classes */
//#include <Xm/FileSB.h>
//#include <Xm/Form.h>
//#include <Xm/PushB.h>
//#include <Xm/RowColumn.h>
//#include <Xm/Separator.h>
//#include <Xm/ToggleB.h>
//#include <Xm/Scale.h>
//#include <Xm/Shell.h>
#include<TextTable.h>
#include<TableMan.h>
/*
** Generated by WorkShop Visual
*/
/*
**LIBS: -lMrm -lXm -lXt -lX11
*/

#include <stdlib.h>
#include <X11/Xatom.h>
#include <X11/Intrinsic.h>
#include <X11/Shell.h>

#include <Mrm/MrmAppl.h>
#include <Xm/Xm.h>
#include <Xm/DialogS.h>
#include <Xm/Form.h>
#include <Xm/Label.h>
#include <Xm/MessageB.h>
#include <Xm/PushB.h>
#include <Xm/RowColumn.h>
#include <Xm/TextF.h>
#include <Xm/ToggleB.h>
#include <Xm/CascadeBG.h>
#include <Xm/LabelG.h>
#include <Xm/SeparatoG.h>
#include <Xm/ToggleBG.h>


/* Header data of program */
#include "color3d.h"
#include "grafik.h"
#include "motif.h"
#include "uil.h"

t_edge edgeinfo;
static int materialnum = 1;
static int changecol   = 1;

void create_cutShell (Widget parent);
void initcut(Widget parent, XtPointer client_data, XtPointer xt_call_data);

extern void XDmanage_link( Widget w, XtPointer client_data, XtPointer call_data);

extern void XDunmanage_link( Widget w, XtPointer client_data, XtPointer call_data);

extern void XDpopup_link( Widget w, XtPointer client_data, XtPointer call_data);

extern void XDpopdown_link( Widget w, XtPointer client_data, XtPointer call_data);

extern void XDmap_link( Widget w, XtPointer client_data, XtPointer call_data);

extern void XDunmap_link( Widget w, XtPointer client_data, XtPointer call_data);

extern void XDenable_link( Widget w, XtPointer client_data, XtPointer call_data);

extern void XDdisable_link( Widget w, XtPointer client_data, XtPointer call_data);

Widget cutShell = (Widget) NULL;
Widget F_cut = (Widget) NULL;
Widget RC_slice = (Widget) NULL;
Widget TT_slices = (Widget) NULL;
Widget TB_slice = (Widget) NULL;
Widget RC_outline = (Widget) NULL;
Widget TB_outline = (Widget) NULL;
Widget RC_opt_outline = (Widget) NULL;
Widget OP_color = (Widget) NULL;
Widget labelColor = (Widget) NULL;
Widget CA_color = (Widget) NULL;
Widget ME_Color = (Widget) NULL;
Widget OP_material = (Widget) NULL;
Widget labelMaterial = (Widget) NULL;
Widget CA_material = (Widget) NULL;
Widget ME_Material = (Widget) NULL;
Widget RC_cut = (Widget) NULL;
Widget TB_schneiden = (Widget) NULL;
Widget RB_def_cut = (Widget) NULL;
Widget TB_def_plane = (Widget) NULL;
Widget TB_def_coord = (Widget) NULL;
Widget RC_coord = (Widget) NULL;
Widget RC_rotate = (Widget) NULL;
Widget SC_x_rotate = (Widget) NULL;
Widget SC_y_rotate = (Widget) NULL;
Widget SC_z_rotate = (Widget) NULL;
Widget labelX = (Widget) NULL;
Widget labelY = (Widget) NULL;
Widget labelZ = (Widget) NULL;
Widget T_punkt1x = (Widget) NULL;
Widget T_punkt1y = (Widget) NULL;
Widget T_punkt1z = (Widget) NULL;
Widget T_punkt2x = (Widget) NULL;
Widget T_punkt2y = (Widget) NULL;
Widget T_punkt2z = (Widget) NULL;
Widget T_punkt3x = (Widget) NULL;
Widget T_punkt3y = (Widget) NULL;
Widget T_punkt3z = (Widget) NULL;
Widget RB_def_cut_nr = (Widget) NULL;
Widget TB_def_nummer = (Widget) NULL;
Widget RC_node_num = (Widget) NULL;
Widget labelNode1 = (Widget) NULL;
Widget labelNode2 = (Widget) NULL;
Widget labelNode3 = (Widget) NULL;
Widget T_punkt1nr = (Widget) NULL;
Widget T_punkt2nr = (Widget) NULL;
Widget T_punkt3nr = (Widget) NULL;
Widget Apply = (Widget) NULL;
Widget Close = (Widget) NULL;
Widget Help = (Widget) NULL;


void create_cutShellCB(Widget w,XtPointer clientData,
		       XtPointer callData)
{
  if ( cutShell == NULL )
    {
      create_cutShell (w);
      init_cut();
    }
  else
    {
      if (XmToggleButtonGetState( widget_transform.TB_schneiden ))
	cutting_on = TRUE;
      XtPopup( cutShell, XtGrabNone );
    }

  C3D_postredisplay();
}


void create_cutShell (Widget parent)
{
  Widget children[16];      /* Children to manage */
  Arg al[64];                    /* Arg List */
  register int ac = 0;           /* Arg Count */
  XtPointer tmp_value;             /* ditto */
  int success;
  MrmType mrm_class;
  Widget messageBox2 = (Widget)NULL;
  Widget label4 = (Widget)NULL;
  Widget label10 = (Widget)NULL;
  Widget label11 = (Widget)NULL;
  Widget label12 = (Widget)NULL;

  XtSetArg(al[ac], XmNallowShellResize, TRUE); ac++;
  cutShell = XmCreateDialogShell ( toplevel,(char *) "cutShell", al, ac );
  ac = 0;
    
  success = MrmFetchWidget ( hierarchy, (char *) "messageBox2", cutShell, &messageBox2, &mrm_class );
  if (success != MrmSUCCESS)
    {
      fprintf(stderr, "Can't fetch widget.\n");
      return;
    }
    
  F_cut = XtNameToWidget(messageBox2, "F_cut") ; 
  RC_slice = XtNameToWidget(F_cut, "RC_slice") ;
  TT_slices = XtNameToWidget(RC_slice, "TT_slices") ; 
  TB_slice = XtNameToWidget(RC_slice, "toggleSlice") ; 
  RC_outline = XtNameToWidget(F_cut, "RC_outline") ; 
  TB_outline = XtNameToWidget(RC_outline, "toggleOutline") ; 
  RC_opt_outline = XtNameToWidget(RC_outline, "rowcolOutline") ; 
  OP_color = XtNameToWidget(RC_opt_outline, "optColor") ; 
  labelColor = XmOptionLabelGadget ( OP_color );
  CA_color = XmOptionButtonGadget ( OP_color );
  XtSetArg(al[ac], XmNsubMenuId, &ME_Color ); ac++;
  XtGetValues(CA_color, al, ac );
  ac = 0;
  OP_material = XtNameToWidget(RC_opt_outline, "optMaterial") ; 
  labelMaterial = XmOptionLabelGadget ( OP_material );
  CA_material = XmOptionButtonGadget ( OP_material );
  XtSetArg(al[ac], XmNsubMenuId, &ME_Material ); ac++;
  XtGetValues(CA_material, al, ac );
  ac = 0;
  RC_cut = XtNameToWidget(F_cut, "RC_cut") ; 
  TB_schneiden = XtNameToWidget(RC_cut, "toggleCut") ; 
  RB_def_cut = XtNameToWidget(RC_cut, "RB_def_cut") ; 
  TB_def_plane = XtNameToWidget(RB_def_cut, "TB_def_plane") ; 
  TB_def_coord = XtNameToWidget(RB_def_cut, "TB_def_coord") ; 
  RC_rotate = XtNameToWidget(RC_cut, "RC_rotate") ;
  SC_x_rotate = XtNameToWidget(RC_rotate, "SC_x_rotate") ;
  SC_y_rotate = XtNameToWidget(RC_rotate, "SC_y_rotate") ;
  SC_z_rotate = XtNameToWidget(RC_rotate, "SC_z_rotate") ;
  RC_coord = XtNameToWidget(RC_cut, "RC_coord") ; 
  label4 = XtNameToWidget(RC_coord, "label4") ; 
  labelX = XtNameToWidget(RC_coord, "labelX") ; 
  labelY = XtNameToWidget(RC_coord, "labelY") ; 
  labelZ = XtNameToWidget(RC_coord, "labelZ") ; 
  label10 = XtNameToWidget(RC_coord, "label10") ; 
  T_punkt1x = XtNameToWidget(RC_coord, "T_punkt1x") ; 
  T_punkt1y = XtNameToWidget(RC_coord, "T_punkt1y") ; 
  T_punkt1z = XtNameToWidget(RC_coord, "T_punkt1z") ; 
  label11 = XtNameToWidget(RC_coord, "label11") ; 
  T_punkt2x = XtNameToWidget(RC_coord, "T_punkt2x") ; 
  T_punkt2y = XtNameToWidget(RC_coord, "T_punkt2y") ; 
  T_punkt2z = XtNameToWidget(RC_coord, "T_punkt2z") ; 
  label12 = XtNameToWidget(RC_coord, "label12") ; 
  T_punkt3x = XtNameToWidget(RC_coord, "T_punkt3x") ; 
  T_punkt3y = XtNameToWidget(RC_coord, "T_punkt3y") ; 
  T_punkt3z = XtNameToWidget(RC_coord, "T_punkt3z") ; 
  RB_def_cut_nr = XtNameToWidget(RC_cut, "RB_def_cut_nr") ; 
  TB_def_nummer = XtNameToWidget(RB_def_cut_nr, "TB_def_nummer") ; 
  RC_node_num = XtNameToWidget(RC_cut, "RC_node_num") ; 
  labelNode1 = XtNameToWidget(RC_node_num, "labelNode1") ; 
  labelNode2 = XtNameToWidget(RC_node_num, "labelNode2") ; 
  labelNode3 = XtNameToWidget(RC_node_num, "labelNode3") ; 
  T_punkt1nr = XtNameToWidget(RC_node_num, "T_punkt1nr") ; 
  T_punkt2nr = XtNameToWidget(RC_node_num, "T_punkt2nr") ; 
  T_punkt3nr = XtNameToWidget(RC_node_num, "T_punkt3nr") ; 
  Apply = XtNameToWidget(messageBox2, "btnApply") ; 
  Close = XtNameToWidget(messageBox2, "btnClose") ; 
  Help = XtNameToWidget(messageBox2, "btnHelp") ; 
  initcut(messageBox2, NULL, NULL);
  XtManageChild(messageBox2);
}

void
initcut( Widget w, XtPointer client_data, XtPointer xt_call_data )
{
  XDdisable_link(w, CA_color, xt_call_data);
  XDdisable_link(w, OP_color, xt_call_data );
  XtSetSensitive(labelMaterial, FALSE );
  XtSetSensitive(OP_material, FALSE );
  XtSetSensitive(TB_def_plane, FALSE );
  XtSetSensitive (TB_def_coord, FALSE );
  XtSetSensitive(T_punkt1x, FALSE);
  XtSetSensitive( T_punkt1y, FALSE );
  XtSetSensitive( T_punkt1z, FALSE );
  XtSetSensitive( T_punkt2x, FALSE );
  XtSetSensitive( T_punkt2y, FALSE );
  XtSetSensitive( T_punkt2z, FALSE );
  XtSetSensitive( T_punkt3x, FALSE );
  XtSetSensitive( T_punkt3y, FALSE );
  XtSetSensitive( T_punkt3z, FALSE);
  XtSetSensitive( T_punkt1nr, FALSE);
  XtSetSensitive( T_punkt1nr, FALSE );
  XtSetSensitive( T_punkt1nr, FALSE);
}

int fill_tt_cuts()
{
  struct listelem *cut;
  t_isocut *tcut;
  int i;
  char Value[4][81];	
  
  XtVaSetValues(TT_slices, BXmNrecomputeLayout, FALSE, NULL);
  XtVaSetValues(TT_slices, BXmNnumRows, g_isocuts.ncuts, NULL);
  if (g_isocuts.cuts != NULL)
  {
     for(cut = g_isocuts.cuts->head, i = 0; cut != NULL; 
         cut = cut->next, i++)
     {
        tcut = (t_isocut *)cut->data;
        sprintf(Value[0], "%d", tcut->nr);
        sprintf(Value[1], "%f", tcut->cplane[0]);
        sprintf(Value[2], "%f", tcut->cplane[1]);
        sprintf(Value[3], "%f", tcut->cplane[2]);
	BXmTextTableSetField(TT_slices, i+1, 1, Value[0]);
	BXmTextTableSetField(TT_slices, i+1, 2, Value[1]);
	BXmTextTableSetField(TT_slices, i+1, 3, Value[2]);
	BXmTextTableSetField(TT_slices, i+1, 4, Value[3]);
     }
   }
   
   XtVaSetValues(TT_slices, BXmNrecomputeLayout, TRUE, NULL);
   BXmTextTableDeselectAll(TT_slices);
  
   return 0;  	
}

void 
cutCB(Widget w, XtPointer clientData,
      XtPointer callData)
{
  MrmType topWidgetClass;
  Widget  cutwid = NULL;

  if ((cutwid == NULL) && 
      (MrmFetchWidget(hierarchy, "topWidgetCut", toplevel,
		      &cutwid, &topWidgetClass)) != MrmSUCCESS)
    {
      fprintf(stderr, "Cutting dialog can't be loaded\n");
    }
  XtManageChild( cutwid );
}

void
setsliceCB(Widget w, XtPointer clientData,
	XtPointer callData)
{
   XmToggleButtonCallbackStruct *cb = (XmToggleButtonCallbackStruct *) callData;
#ifdef DEBUG
   printf("We are in set slices callback: %s\n", (cb->set) ? "true" : "false");
#endif 
}

int add_slice()
{
   t_isocut new_cut;
   int numcuts;
   int i,j;

   new_cut.nr = g_isocuts.ncuts + 1;
   new_cut.on = TRUE;
   new_cut.cplane[0] = g_transform.norm[0];  
   new_cut.cplane[1] = g_transform.norm[1];
   new_cut.cplane[2] = g_transform.norm[2];
   new_cut.cplane[3] = g_transform.d;
   new_cut.field     = TRUE;
 
   add_cut( &(g_isocuts.cuts), &new_cut, &g_isocuts.ncuts );
   C3D_updatecut(g_isocuts.cuts, TRUE);
   return 0;    
}

static int cmp_slice(const void* cmp, const void *data)
{
   int *nr1, nr2;
   t_isocut *cmpcut, *cut;

   nr1 = (int *) cmp;
   cut = (t_isocut*) data;
   nr2 = cut->nr;
   if (*nr1 > nr2)
	return 1;
   else if (*nr1 < nr2)
	return -1;
   else
        return 0;
}

int delete_slice(int linenr)
{
   gdelitem( g_isocuts.cuts, (void*) &linenr, cmp_slice );
   --g_isocuts.ncuts;
   return 0;
}

void addsliceCB(Widget w, XtPointer clientData, XtPointer callData)
{
   add_slice();
   fill_tt_cuts();
}

void deletesliceCB(Widget w, XtPointer clientData, XtPointer callData)
{
   int i, nrows;
   char *strptr;

   XtVaGetValues( TT_slices, BXmNnumRows,
                  &nrows, NULL );
   for ( i = 1; i <= nrows; i++ )
   {
      if ( BXmTextTablePosIsSelected( TT_slices, i ) == True )
      { 
         BXmTextTableGetField( TT_slices, i, 1, FALSE,
                             &strptr );
         if( delete_slice( atoi(strptr) ))
               warning("No slice left to delete");
      }
   }
   fill_tt_cuts();
}

void destroy_cut( void *data )
{
}

int
add_cut( struct list **lcut, t_isocut *new_cut, int *numcuts )
{
   t_isocut *ncut;
   int i,j;
   i = j = 0;
   
   /* allocate new iso */
   NEW( ncut );
  
   ncut->mat = (t_cut *) ALLOC( sizeof( ncut->mat[0] ) * g_geodat.nstoff );
   j = *numcuts;
   ncut->on = new_cut->on;
   ncut->nr = new_cut->nr;
   ncut->cplane[0] = new_cut->cplane[0];
   ncut->cplane[1] = new_cut->cplane[1];
   ncut->cplane[2] = new_cut->cplane[2];
   ncut->cplane[3] = new_cut->cplane[3];
   ncut->field     = new_cut->field;
	
   for ( i = 0; i < g_geodat.nstoff; i++ )
   {
      (ncut->mat[i]).vertices = NULL;
      (ncut->mat[i]).vals = NULL;
      
      (ncut->mat[i]).ntri = 0;
   }
   if ( *lcut == NULL )
   {
      NEW( *lcut );
      glistinit( *lcut, destroy_cut );
   }
   (*lcut)->head = gaddend( *lcut, gnewitem( (void*) ncut));
   (*numcuts)++; 	
}


void 
setoutlineCB(Widget w, XtPointer clientData,
	     XtPointer callData)
{
  XmToggleButtonCallbackStruct *cb = (XmToggleButtonCallbackStruct *) callData;
#ifdef DEBUG
  printf("We are in set outline callback: %s\n", (cb->set) ? "true":"false");
#endif
  XtSetSensitive( CA_color, TRUE );
  XtSetSensitive( OP_color, TRUE );
  XtSetSensitive( OP_material, TRUE );
  XtSetSensitive( labelMaterial, TRUE );
  if (cb->set)
    {
      edgeinfo.edge_on = TRUE;
    }
  else
    {
      edgeinfo.edge_on = FALSE;
    }
}

void
changeoutcolorCB( Widget w, XtPointer clientData,
		  XtPointer callData )
{
  int ncol, i;
  XmRowColumnCallbackStruct *cbs = ( XmRowColumnCallbackStruct *) callData;
#ifdef DEBUG
  printf( " %s selected\n", XtName( cbs->widget ));
#endif
  ncol = 8;
  for (i = 0; i < ncol; i++)
    {
      char widname[] = "drawbutton";
      char num[4];
      sprintf(num,"%i",i);
      strcat(widname, num);
      if (strcmp(widname, XtName(cbs->widget)) == 0)
	changecol = i+1;
    }
#ifdef DEBUG
  printf("Choosing color: %i\n", changecol);
#endif
}

void
setcolorsCB( Widget w, XtPointer clientData,
		XtPointer callData )
{
  Widget *drawbuttons = NULL;
  Pixel color;
  char matstr[20];
  int ncolors = 0;
  int i = 0;
 
  /* get number of colors */
  ncolors = 8;
 
  drawbuttons = (Widget *) XtMalloc( sizeof(Widget) * ncolors);
  for (i = 0; i < ncolors; i++)
    {
      char num[4]; 
      char label[] = "drawbutton";
      sprintf(num, "%i", i);
      strcat(label, num);
      drawbuttons[i] = XtCreateManagedWidget( label, xmPushButtonWidgetClass, w,
      					      NULL, 0);
      // XtVaSetValues( drawbuttons[i], XmNbackground, color, NULL);
    }
}

void
setmaterialsCB( Widget w, XtPointer clientData,
		XtPointer callData)
{
  Widget *labels = NULL;
  XmString namemat;
  char matstr[20];
  int nmaterials = 0;
  int i = 0;
  
  /* get number of materials */
  nmaterials = g_geodat.nstoff;
 
  labels = (Widget *) XtMalloc( sizeof(Widget) * nmaterials);
  for (i = 0; i < nmaterials; i++)
    {
      char num[4]; 
      char label[] = "label";
      sprintf(num, "%i", i);
      strcat(label, num);
      labels[i] = XtCreateManagedWidget( label, xmPushButtonWidgetClass, w,
					 NULL, 0);
      sprintf(matstr,"Material %i", i+1);
      namemat = XmStringCreateLtoR(matstr, XmFONTLIST_DEFAULT_TAG);
      XtVaSetValues( labels[i], XmNlabelString, namemat, NULL);
    }
}

void
getmaterialCB( Widget w, XtPointer clientData,
	       XtPointer callData )
{
  int nmat, i;
  XmRowColumnCallbackStruct *cbs = ( XmRowColumnCallbackStruct *) callData;
#ifdef DEBUG
  printf( " %s selected\n", XtName( cbs->widget ));
#endif
  nmat = g_geodat.nstoff;
  for (i = 0; i < nmat; i++)
    {
      char widname[] = "label";
      char num[4];
      sprintf(num,"%i",i);
      strcat(widname, num);
      if (strcmp(widname, XtName(cbs->widget)) == 0)
	materialnum = i+1;
    }
}

void initrotxCB( Widget w, XtPointer clientData,
	XtPointer callData )
{
}

void initrotyCB( Widget w, XtPointer clientData,
	XtPointer callData )
{
}

void initrotzCB( Widget w, XtPointer clientData,
	XtPointer callData )
{
}

extern float xr[8], yr[8], zr[8];
extern t_bool y_rotation;

void changeXRCB( Widget w, XtPointer clientData,
	XtPointer callData )
{
	float xr_old;
	XmScaleCallbackStruct *cbs = ( XmScaleCallbackStruct* ) callData;
	xr_old = xr[0];
	xr[0] += ((float)cbs->value - xr_old); 
	C3D_postredisplay();
}

void changeYRCB( Widget w, XtPointer clientData,
	XtPointer callData )
{
	float yr_old;
	XmScaleCallbackStruct *cbs = ( XmScaleCallbackStruct* ) callData;
	yr_old = yr[0];
	yr[0] += ((float)cbs->value - yr_old );
	y_rotation = TRUE;
	C3D_postredisplay();
}

void changeZRCB( Widget w, XtPointer clientData,
	XtPointer callData )
{
	float zr_old;
	XmScaleCallbackStruct *cbs = ( XmScaleCallbackStruct* ) callData;
	zr_old = zr[0];
	zr[0] += ((float)cbs->value - zr_old);
	C3D_postredisplay();
}

void 
cutapplyCB( Widget w, XtPointer clientData, 
	    XtPointer callData)
{
  if ( changecol )
    edgeinfo.edgecolor = changecol;

  if ( XmToggleButtonGetState( widget_transform.TB_schneiden ) )
    {
      g_transform.schneiden_on = TRUE;

      if (XmToggleButtonGetState(widget_transform.TB_def_plane))
	{
	  cutting_on = TRUE;
	  schneide();
	}
      else if (XmToggleButtonGetState(widget_transform.TB_def_nummer) ||
	       XmToggleButtonGetState(widget_transform.TB_def_koord))
	{
	  get_schnitt_koord();
	  schneide();
	}
    }

  if ( materialnum && g_transform.schneiden_on )
    {
      find_edges( materialnum );
    }
  
  
  C3D_postredisplay();
}

void
cutcloseCB( Widget w, XtPointer clientData,
	    XtPointer callData )
{
#ifdef DEBUG
  printf("We are in close callback\n");
#endif
  cutting_on = FALSE;

  /* close cut dialog box */
  XtPopdown( cutShell );
}

void 
cuthelpCB ( Widget w, XtPointer clientData, 
	    XtPointer callData )
{
#ifdef DEBUG
  printf("We are in help callback\n");
#endif
  
}
