/* XPM */
static char *zoominf[] = {
/* width height ncolors chars_per_pixel */
"64 46 17 1",
/* colors */
"  c #0c0a0c",
"# c #8c8ebc",
"a c #54566c",
"b c #1c1a74",
"c c none",
"d c #2c2e54",
"e c #0c0e34",
"f c #a4a2a4",
"g c #24228c",
"h c #fcfafc",
"i c #6c6e94",
"j c #1c1e8c",
"k c #d4d6e4",
"l c #2c2e6c",
"m c #14124c",
"n c #a4a2c4",
"o c #000000",
/* pixels */
"ccccccccccccccccccccccccccccccccccccccccccffaaiiffcccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccnilgbggbgdbaafccccccccccc",
"cccccccccccccccccccccccccccccccccccccfagjjgjjggjgjjbbafccccccccc",
"ccccccccccccccccccccccccccccccccccccfgggjjbgggggggjgjjgicccccccc",
"ccccccccccccccccccccccccccccccccccnibgbgggbmmeemmbggjggjancccccc",
"ccccccccccccccccccccccccccccccccccajgjgbmeeeeeeeemebgjjgjafccccc",
"cccccccccccccccccccccccccccccccccajjjgbee mmmddmmmeembggjgaccccc",
"cccccccccccccccccccccccccccccccciljggmeemdii####iileeebjgjjacccc",
"cccccccccccccccccccccccccccccccfggjgmemdi#########nigeebjgjbfccc",
"cccccccccccccccccccccccccccccccagjjbeel##############ieejgjggccc",
"ccccccccccccccccccccccccccccccfggjgemi############nchkfemjgjbfcc",
"ccccccccccccccccccccccccccccccajjgmel############nkhhhh#ebjgblcc",
"ccccccccccccccccccccccccccccccdjgbemi############nhhhhhkdmgjbgfc",
"cccccccccccccccccccccccccccccfbjgbea########dedi#nhhhhhhimjjgbac",
"cccccccccccccccccccccccccccccajjjbmi########d  ##nkhhhhkibgjjjdc",
"cccccccccccccccccccccccccccccajjgbm#########d  i##nhhhkn#lbjgjmf",
"cccccccccccccccccccccccccccccajjjmd######ddd   edd#chkn##ibjjjmi",
"cccccccccccccccccccccccccccccdjjjma#####a         i#nn###ibgjgma",
"cccccccccccccccccccccccccccccajjjbi#n####  e     m#######ibjjged",
"cccccccccccccccccccccccccccccabjgbg#######i#e  i#########gbbgjmd",
"cccccccccccccccccccccccccccccibjjbb#####f###d  ##########gjggged",
"cccccccccccccccccccccccccccccfbgjjbi########d mi#########djjjgda",
"cccccccccccccccccccccccccccccfgjjgbin########ii#######n#ibjggbea",
"ccccccccccccccccccccccccccccfaejjjjgi###################ajjjgeef",
"ccccccccccccccccccccccccccfadbmbjgjjg##################ibjjgbemn",
"ccccccccccccccccccccccccfadgggjmjjgjgi##n#############ibjgjjmeac",
"cccccccccccccccccccccccadbjgjjjmmgjgjbi######n###n###ibjgjgbeefc",
"cccccccccccccccccccccfdbjjgjjjjmebjgjgbai#n########iigjjgjgeedcc",
"cccccccccccccccccccflmjjggjjbmmbmejjgjgjlii#######igjgjjjbeeefcc",
"cccccccccccccccccfadjgjjjjjbmbjjbembjgjgjlbgggiagjbjjjjgbmeeaccc",
"cccccccccccccccfadggjgjjjbmmjjbmaimebgjgjgjgjgjjjgjgbgbbme acccc",
"ccccccccccccccaddgjjjjjbmmbgjmdfccfeemggjjgjgjgjgjggjgbeeeaccccc",
"ccccccccccccadbjgjjjjbmmbgblbfcccccfeeembggjgjjjjbjjbeeeeacccccc",
"ccccccccccadljgjgjjjmmbjjgdafcccccccfbe membbgbbbbmeeeeeancccccc",
"cccccccnfdbjgjjjjjmmbjbbdafcccccccccccieeeeeeee  eee  bfcccccccc",
"ccccccfamgggjgjjmmbjjbeafccccccccccccccnib  eeeeeeeeafcccccccccc",
"ccccfambjggjgjbmmjjbmafcccccccccccccccccccffaaaaaifncccccccccccc",
"ccfabbjgjjjjbmmbjgbdfccccccccccccccccccccccccccccccccccccccccccc",
"fadljjgjjjjmmbjbmbffcccccccccccccccccccccccccccccccccccccccccccc",
"dbjjjgjjjmmbjbbdiccccccccccccccccccccccccccccccccccccccccccccccc",
"dlgggjjbmmjjbbaccccccccccccccccccccccccccccccccccccccccccccccccc",
"fdjjjbmmbjjmafcccccccccccccccccccccccccccccccccccccccccccccccccc",
"cdlbmmbjbdafcccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cfembjbbdfcccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccadglaicccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccidacccccccccccccccccccccccccccccccccccccccccccccccccccccccccc"
};

/* XPM */
static char *zoomoutf[] = {
/* columns rows colors chars-per-pixel */
"64 46 17 1",
"  c #020202",
". c #0c0e34",
"X c #14124c",
"o c #1c1a74",
"O c #2c2e5a",
"+ c #54566c",
"@ c #1c1e8c",
"# c #24228c",
"$ c #6c6e95",
"% c #7f81ab",
"& c #8b8dbb",
"* c #a3a1a4",
"= c #a4a2c4",
"- c none",
"; c #d4d6e4",
": c #fcfafc",
"> c None",
/* pixels */
"------------------------------------------**++$$**--------------",
"---------------------------------------*$O#o##o#Oo++*-----------",
"-------------------------------------*+#@@#@@##@#@@oo+*---------",
"------------------------------------*###@@o#######@#@@#$--------",
"----------------------------------=$o#o###oXX..XXo@#@##@+=------",
"----------------------------------+@#@#oX........X.o#@@#@+*-----",
"---------------------------------+@@@#o.. XXXOOXXX..Xo##@#+-----",
"--------------------------------$O@##X..XO$$&&&&$$OX..o@#@@+----",
"-------------------------------*##@#X.XO$&&&&&&&&&=$#..o@#@o*---",
"-------------------------------+#@@@.XO&&&&&&&&&&&&&&$..@#@##---",
"------------------------------*##@#.X$&&&&&&&&&&&&=-:;*.X@#@o*--",
"------------------------------+@@#X.O&&&&&&&&&&&&=;::::&.o@#oO--",
"------------------------------O@#o.X$&&&&&&&&&&&&=:::::;OX#@o#*-",
"-----------------------------*o@#o.+&&&&&&&&&&&%&=::::::$X@@#o+-",
"-----------------------------+@@@oX$&&&&&&&&&&&&&=;::::;$o#@@@O-",
"-----------------------------+@@#oX&&&&&&&&&$%$$&&=:::;=&Oo@#@X*",
"-----------------------------+@@@XO&&&&&&          -:;=&&$o@@@X$",
"-----------------------------O@@@X+&&&&&+          &==&&&$o#@#X+",
"-----------------------------+o@@o$&=&&&&          &&&&&&$o@@#.O",
"-----------------------------+o@#o#&&&&&&&$&&$$$&&&&&&&&&#oo#@XO",
"-----------------------------$o@@oo&&&&&*&&&&&%&&&&&&&&&&#@###.O",
"-----------------------------*o#@@o$&&&&&&&&&&&&&&&&&&&&&O@@@#O+",
"-----------------------------*#@@#o$=&&&&&&&&&&&&&&&&&=&$o@#oo.+",
"----------------------------*+.@@@@#$&&&&&&&&&&&&&&&&&&&+@@@#..*",
"--------------------------*+OoXo@#@@#&&&&&&&&&&&&&&&&&&$o@@#o.X*",
"------------------------*+O###@X@@#@#$&&=&&&&&&&&&&&&&$o@#@@X.+-",
"-----------------------+Ooo#@@@XX#@#@o$&&&&&&=&&&=&&&$o@#@#o..*-",
"---------------------*Oo@@#@@@@X.o@#@#o+$&=&&&&&&&&$$#@@#@#..O--",
"-------------------*OX@@##@@oXXoX.@@#@#@o$$=&&&&&&$#@#@@#o...*--",
"-----------------*+O@#@@@@@oXo@@o.Xo@#@#@Oo###$+#@o@@@@#oX..+---",
"---------------*+O##@#@@@oXX@@oX+$X.o#@#@#@#@#@@@#@#o#ooX. +----",
"--------------+OO#@@@@@oXXo#@XO*--*..X##@@#@#@#@#@##@#o...+-----",
"------------+Oo@#@@@@oXXo#oOo*-----*...Xo#####@@@o@@O....+------",
"----------+OO@#@#@@@XXo@@#O+*-------*o. X.Xoo#o#ooX.....+=------",
"-------=*Oo@#@@@@@XXo@ooO+*-----------$........  ... .o*--------",
"------*+X###@#@@XXo@@o.+*--------------=$o  ........+*----------",
"----*+Xo@##@##oXX@@oX+*-------------------**+++++$*=------------",
"--*+oo@#@@@@oXXo@#oO*-------------------------------------------",
"*+OO@@#@@@@X.o@oXo**--------------------------------------------",
"Oo@@@#@@@XXo@ooO$-----------------------------------------------",
"OO###@@oXX@@oo+-------------------------------------------------",
"*O@@@oXXo@@X+*--------------------------------------------------",
"-OOoXXo@oO+*----------------------------------------------------",
"-*.Xo@ooO*-------------------------------;----------------------",
"--+O#O+$--------------------------------------------------------",
"---$O+----------------------------------------------------------"
};
